export type PrepVillaFaq = {
  category: string;
  question: string;
  answer: string;
};

export const PREPVILLA_FAQS: PrepVillaFaq[] = [
  { category: "Getting started", question: "What is PrepVilla?", answer: "PrepVilla is a tutor marketplace that helps students discover verified tutors, request lessons, communicate, pay securely, and manage learning from one account." },
  { category: "Getting started", question: "Who can use PrepVilla?", answer: "You can register as a student looking for lessons or as a tutor offering lessons. Platform administrators manage verification and support workflows." },
  { category: "Getting started", question: "How do I create an account?", answer: "Choose Sign up, select Student or Tutor, enter the requested details, verify your account when prompted, and complete the profile for your role." },
  { category: "Getting started", question: "Can I sign up or log in with Google?", answer: "Yes. Choose the Google option on the sign-up or login page and complete Google's authentication flow." },
  { category: "Getting started", question: "Can one email be used for both a student and tutor account?", answer: "An email identifies one PrepVilla account. Use a different email if you need a separate account with another role." },
  { category: "Getting started", question: "Where do I manage my account?", answer: "Open Dashboard and use Profile for personal information, Settings for account actions, and Billing & Subscription for packages and payment history." },
  { category: "Getting started", question: "Does PrepVilla provide online and face-to-face lessons?", answer: "Tutors can indicate whether they offer face-to-face lessons, webcam lessons, or both. Check the tutor profile before booking." },
  { category: "Getting started", question: "How do I contact PrepVilla?", answer: "Use Feedback for suggestions, Complaint for service complaints, Issues for problems requiring investigation, or the Support page where available." },

  { category: "Account and security", question: "I forgot my password. What should I do?", answer: "Use Forgot password on the login page, request a reset code, and follow the instructions sent to your registered email." },
  { category: "Account and security", question: "Why do I need an OTP?", answer: "One-time codes help verify sensitive actions such as account activation, password changes, email changes, and phone changes." },
  { category: "Account and security", question: "My OTP expired. Can I request another one?", answer: "Yes. Use the resend option after the resend timer ends, then enter the newest code you receive." },
  { category: "Account and security", question: "Why am I being logged out?", answer: "Your session may have expired, your refresh token may no longer be valid, or your account status may have changed. Log in again or reset your password if needed." },
  { category: "Account and security", question: "How do I change my email address?", answer: "Open Dashboard Settings and follow the email-change verification flow. Approved tutors may need support to change identity-backed details." },
  { category: "Account and security", question: "How do I change my mobile number?", answer: "Use Dashboard Settings. Some mobile-number changes require an OTP or admin approval, especially when the number is tied to verified information." },
  { category: "Account and security", question: "Can I temporarily freeze my account?", answer: "Yes. Account controls in Settings can start the freeze flow. A frozen account cannot perform normal platform actions until it is unfrozen." },
  { category: "Account and security", question: "Can I delete my account?", answer: "You can start account deletion from Settings. Follow the confirmation steps carefully because deletion may affect access to profile and historical data." },
  { category: "Account and security", question: "What should I do if I notice suspicious activity?", answer: "Change your password, secure your email account, sign out of unfamiliar sessions where possible, and raise an urgent Issue for the admin team." },
  { category: "Account and security", question: "Why are some profile fields locked?", answer: "Identity-backed fields can be locked after verification to protect trust and prevent an approved profile from being changed into another identity." },

  { category: "Students", question: "How do I find a tutor?", answer: "Use tutor search to browse available tutors and filter by subject, rate, location, language, availability, and other displayed criteria." },
  { category: "Students", question: "What does a verified tutor badge mean?", answer: "It means PrepVilla has reviewed the tutor's submitted verification information. Students should still discuss lesson expectations before booking." },
  { category: "Students", question: "How do I view a tutor's full profile?", answer: "Select a tutor card from search results to see their biography, subjects, languages, rate, lesson methods, verification status, and available actions." },
  { category: "Students", question: "How do favourites work?", answer: "Save a tutor to Favourites from the tutor experience, then open Dashboard > Favourites to return to that tutor later." },
  { category: "Students", question: "Can I message a tutor before booking?", answer: "Where the contact action is available, you can start a conversation to discuss the subject, goals, timing, location, or webcam arrangements." },
  { category: "Students", question: "Do students need verification?", answer: "PrepVilla may require student profile and identity details before allowing sensitive marketplace actions. Follow the verification prompts shown in your account." },
  { category: "Students", question: "Can I update my student profile?", answer: "Yes. Open Dashboard > Profile to update editable information. Verified or sensitive fields may use a separate approval flow." },
  { category: "Students", question: "How do I know a tutor's lesson rate?", answer: "The tutor's displayed hourly rate appears on their public profile and is used when the lesson checkout is created." },
  { category: "Students", question: "What does 'first lesson free' mean?", answer: "It means the tutor has chosen to advertise a free first lesson. Confirm the exact scope and conditions with the tutor before the booking." },
  { category: "Students", question: "How do I leave a tutor review?", answer: "After an eligible lesson is completed, use the review action to submit a rating and comment about your experience." },

  { category: "Tutors", question: "How do I become visible to students?", answer: "Complete your tutor profile, submit the required verification details and documents, receive approval, and ensure the profile is listed." },
  { category: "Tutors", question: "What information is required for tutor verification?", answer: "The verification flow may request identity information, NIN, BVN, qualification details, profile information, and supporting documents." },
  { category: "Tutors", question: "How long does tutor verification take?", answer: "Review time depends on submission quality and verification-provider availability. Track the current status from Dashboard > Verification." },
  { category: "Tutors", question: "What should I do if verification is rejected?", answer: "Read the displayed decision or notes, correct inaccurate or incomplete information where allowed, and resubmit or contact support." },
  { category: "Tutors", question: "Can I edit my profile after approval?", answer: "Public teaching information can remain editable where allowed. Verified identity details may be locked and require support review to change." },
  { category: "Tutors", question: "How do I set my hourly rate?", answer: "Open Dashboard > Profile, enter your rate in the Tutor Profile section, and save the changes." },
  { category: "Tutors", question: "How do I add subjects and languages?", answer: "Use the subject and language selectors in Dashboard > Profile. Selected items appear as removable tags inside each field." },
  { category: "Tutors", question: "How do I set availability?", answer: "Open Dashboard > Availability and add the times when students can request lessons. Avoid overlapping slots." },
  { category: "Tutors", question: "How do I accept or reject a booking?", answer: "Open Dashboard > Bookings and use the available action on a requested booking. The student will see the resulting status." },
  { category: "Tutors", question: "How do I enable webcam lessons?", answer: "Enable Webcam under Teaching Methods in your tutor profile. The Video Room page is available for supported online lesson workflows." },
  { category: "Tutors", question: "Why do I need bank details?", answer: "Approved bank details are required so PrepVilla can transfer the tutor share of eligible lesson payments after release conditions are met." },
  { category: "Tutors", question: "Can an unverified tutor receive payouts?", answer: "No. Tutor verification and valid payout bank details are required before a lesson payout can be processed." },

  { category: "Bookings and lessons", question: "How do I request a lesson?", answer: "Open a tutor profile, choose the available booking action, provide the lesson type, requested time or slot, and any helpful notes." },
  { category: "Bookings and lessons", question: "What does 'requested' mean?", answer: "The student has sent a booking request and the tutor has not yet accepted or rejected it." },
  { category: "Bookings and lessons", question: "What does 'confirmed' mean?", answer: "The tutor accepted the request and the lesson is scheduled for the agreed time." },
  { category: "Bookings and lessons", question: "Can a booking be cancelled?", answer: "Cancellation is available when the booking's current state permits it. Open the booking to see the actions available to your role." },
  { category: "Bookings and lessons", question: "Why can I not mark a lesson complete early?", answer: "Completion is only available after the scheduled lesson end time and after the student payment has been confirmed." },
  { category: "Bookings and lessons", question: "Who confirms lesson completion?", answer: "Both participants can record completion. The student's confirmation authorises release of the tutor payout for the paid lesson." },
  { category: "Bookings and lessons", question: "What if the lesson did not take place?", answer: "Do not confirm completion. Contact the other participant and submit a Complaint or Issue with the booking reference if admin review is needed." },
  { category: "Bookings and lessons", question: "Where can I see past bookings?", answer: "Open Dashboard > Bookings and use the status filters to view completed, cancelled, or rejected records." },
  { category: "Bookings and lessons", question: "Can I change the time after a tutor confirms?", answer: "Coordinate with the other participant through Messages. If the booking cannot be changed in the interface, cancel when permitted and create a new request." },
  { category: "Bookings and lessons", question: "What should booking notes contain?", answer: "Include the subject, topic, learning goal, preferred lesson method, and any preparation the tutor should know about." },

  { category: "Payments and payouts", question: "How are payments processed?", answer: "PrepVilla uses Flutterwave checkout for supported payment methods and verifies successful transactions on the server before recording value." },
  { category: "Payments and payouts", question: "Can I pay by bank transfer?", answer: "If Flutterwave offers Bank Transfer during checkout, follow the displayed account and timing instructions. The payment is confirmed after provider verification." },
  { category: "Payments and payouts", question: "Why is my payment still pending?", answer: "Bank transfers and some payment methods can complete asynchronously. Wait briefly, refresh the relevant page, and raise an Issue with the transaction reference if it remains pending." },
  { category: "Payments and payouts", question: "Money was deducted but PrepVilla shows no payment. What should I do?", answer: "Do not pay again immediately. Raise an urgent Issue with the Flutterwave transaction reference, amount, date, and payment purpose so the team can reconcile it." },
  { category: "Payments and payouts", question: "Where can I see subscription payments?", answer: "Open Dashboard > Billing & Subscription to view checkout attempts, payment status, plan, amount, and activation dates." },
  { category: "Payments and payouts", question: "How is a lesson payment divided?", answer: "PrepVilla records a 5% platform fee and a 95% tutor payable amount from a successfully verified lesson payment." },
  { category: "Payments and payouts", question: "When is the tutor's 95% released?", answer: "The tutor amount is held until the paid lesson has ended and the student confirms completion. The payout is then submitted to the tutor's verified bank account." },
  { category: "Payments and payouts", question: "Why is a tutor payout processing?", answer: "A submitted bank transfer can remain pending while Flutterwave and the receiving bank process it. PrepVilla updates the status after provider confirmation." },
  { category: "Payments and payouts", question: "What happens if a tutor payout fails?", answer: "The failure is recorded for investigation. Raise an Issue with the booking or payout reference rather than changing bank details repeatedly." },
  { category: "Payments and payouts", question: "Can a student release payment before the lesson ends?", answer: "No. The completion action is restricted until after the scheduled lesson end time." },
  { category: "Payments and payouts", question: "Should I send money directly to a tutor?", answer: "Use the payment flow shown by PrepVilla for platform bookings. Off-platform payments cannot be protected, verified, or reconciled by PrepVilla." },

  { category: "Subscriptions", question: "Where do I choose a subscription package?", answer: "Open Dashboard > Billing & Subscription to compare available plans and start checkout." },
  { category: "Subscriptions", question: "Who can buy a PrepVilla subscription?", answer: "Student and tutor accounts can use the subscription packages offered for their role. Admin accounts cannot purchase marketplace packages." },
  { category: "Subscriptions", question: "How long does a paid package last?", answer: "The Billing page displays the duration and expiry date for each package. Current paid packages are presented as 30-day access." },
  { category: "Subscriptions", question: "Can I use the free package more than once?", answer: "No. The free introductory package can be activated once per eligible account." },
  { category: "Subscriptions", question: "When does a subscription become active?", answer: "A free plan activates immediately. A paid plan activates after Flutterwave confirms the transaction and PrepVilla records it as completed." },
  { category: "Subscriptions", question: "Are subscriptions renewed automatically?", answer: "Hosted checkout does not silently charge a new renewal without an authorised recurring payment method. Return to Billing when renewal is required." },
  { category: "Subscriptions", question: "Can I transfer a subscription to another account?", answer: "No. Subscription access and payment history are tied to the purchasing account." },
  { category: "Subscriptions", question: "My subscription payment succeeded but the plan is not active. What should I do?", answer: "Refresh Billing first. If it is still missing, raise an Issue with the transaction reference so the payment can be verified and reconciled." },

  { category: "Messages and video", question: "How do Messages work?", answer: "Dashboard > Messages lists your conversations. Open a conversation to read and send messages to the student or tutor involved." },
  { category: "Messages and video", question: "Why can I not start a conversation?", answer: "Your account may need verification, the tutor may be unavailable, or the related interaction may not permit contact. Follow any message shown on the page." },
  { category: "Messages and video", question: "Are messages delivered in real time?", answer: "PrepVilla uses a real-time messaging connection when available and retains conversation messages in the platform." },
  { category: "Messages and video", question: "How do I join a webcam lesson?", answer: "Use the video-room action associated with the supported tutor or confirmed online lesson and allow browser camera and microphone permissions." },
  { category: "Messages and video", question: "My camera or microphone is not working. What should I check?", answer: "Check browser permissions, close other apps using the device, confirm the correct input is selected, and reload the video room." },
  { category: "Messages and video", question: "Can I join a video room before the lesson?", answer: "Room access can be limited to the lesson participants and the permitted time window around a confirmed booking." },
  { category: "Messages and video", question: "What browser should I use for video lessons?", answer: "Use a current version of a major browser with camera, microphone, WebRTC, and secure-site permissions enabled." },
  { category: "Messages and video", question: "What should I do about abusive messages?", answer: "Keep the conversation record, stop engaging, and submit a Complaint or urgent Issue with the relevant user or booking details." },

  { category: "Support and safety", question: "What is the difference between Feedback, Complaint, and Issues?", answer: "Feedback is for ideas and suggestions. Complaint is for dissatisfaction or conduct concerns. Issues is for account, technical, booking, payment, or security problems needing admin investigation." },
  { category: "Support and safety", question: "What should I include in a support request?", answer: "Include a clear title, dates, what happened, what you expected, any error message, and relevant booking, payment, transaction, or payout reference." },
  { category: "Support and safety", question: "How do I track a submitted request?", answer: "A successful submission returns a PrepVilla ticket number. Keep it for follow-up with the support team." },
  { category: "Support and safety", question: "Should I include passwords or OTPs in a request?", answer: "No. Never send your password, OTP, complete card details, or other authentication secrets in any support form or message." },
  { category: "Support and safety", question: "How do I report a tutor or student?", answer: "Submit a Complaint with the participant name and booking reference, describe the conduct factually, and retain relevant messages or evidence." },
  { category: "Support and safety", question: "How do I report a payment or account-security emergency?", answer: "Use Issues, select the closest category, choose Urgent severity, and provide a transaction reference without including secret banking credentials." },
  { category: "Support and safety", question: "Can support change verified details?", answer: "Support can review a request to correct locked details. Approval depends on identity checks and the evidence provided." },
  { category: "Support and safety", question: "Why should I keep activity on PrepVilla?", answer: "Platform bookings, messages, payments, and confirmations create records that help support investigate disputes and protect participants." },
];
