# Generated by Django 5.1.6 on 2026-02-14 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('timezone', models.CharField(max_length=60)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether email is verified via OTP')),
                ('is_frozen', models.BooleanField(default=False, help_text='Whether account is temporarily frozen')),
                ('frozen_until', models.DateTimeField(blank=True, help_text='When freeze ends (if frozen)', null=True)),
                ('is_pending_deletion', models.BooleanField(default=False, help_text='Whether account deletion is requested')),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, help_text='When account will be permanently deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_salt', models.CharField(max_length=32)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=140)),
                ('bio', models.TextField()),
                ('subjects_csv', models.TextField()),
                ('hourly_rate_cents', models.IntegerField()),
                ('languages_csv', models.TextField()),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('home_state', models.CharField(blank=True, default='', max_length=120)),
                ('home_city', models.CharField(blank=True, default='', max_length=120)),
                ('verification_status', models.CharField(default='not_submitted', max_length=20)),
                ('is_listed', models.BooleanField(default=False)),
                ('profile_photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('school_name', models.CharField(blank=True, default='', max_length=255)),
                ('school_address', models.CharField(blank=True, default='', max_length=255)),
                ('principal_name', models.CharField(blank=True, default='', max_length=255)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('nin_number', models.CharField(blank=True, default='', max_length=50)),
                ('document_urls', models.TextField(blank=True, default='', help_text='Comma separated URLs')),
                ('response_time', models.CharField(blank=True, default='', help_text='e.g., 2 hours', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='tutor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutorprofile'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='requested', max_length=20)),
                ('lesson_type', models.CharField(default='Lesson', max_length=100)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('requested_from', models.DateTimeField(blank=True, null=True)),
                ('requested_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=100)),
                ('school_address', models.CharField(blank=True, max_length=200)),
                ('principal_name', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('nin_number', models.CharField(blank=True, max_length=20)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('document_urls', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('tutor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.booking')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'tutor_profile', 'student_user')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tutors', to=settings.AUTH_USER_MODEL)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.tutorprofile')),
            ],
            options={
                'unique_together': {('student_user', 'tutor_profile')},
            },
        ),
    ]
