# Generated by Django 5.1.6 on 2026-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appuser_address_appuser_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentverificationrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='studentverificationrequest',
            name='city',
            field=models.CharField(default='', help_text='Student city', max_length=100),
        ),
    ]
