# Generated by Django 5.1.6 on 2026-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_studentverificationrequest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentverificationrequest',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Student city', max_length=100),
        ),
    ]
