# Generated by Django 5.1.6 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_conversation_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="home_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="state_of_origin",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]

