# Generated by Django 5.1.6 on 2026-03-04

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_me_otp_challenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteTutor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_tutors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="core.tutorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("student_user", "tutor_profile")},
            },
        ),
    ]
