# Generated by Django 5.1.6 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_favoritetutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="first_lesson_free",
            field=models.BooleanField(default=False),
        ),
    ]
